### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by husseinmarah** [fhemberger/mqtt_exporter#3]
Hi,
I wanted to test your exporter, but when I run the python code I got errors, please if you have any idea about these errors, give me a clue.
I tried to execute the program by using both versions of Python 2.7 and 3, and in every case I get different error messages.
Python 2.7
![Screenshot from 2020-12-17 20-48-10](https://user-images.githubusercontent.com/10763642/102536396-d610ad80-40a9-11eb-9c9d-afab0dd39adf.png)

Python 3.6.9
![Screenshot from 2020-12-17 20-48-57](https://user-images.githubusercontent.com/10763642/102536421-e163d900-40a9-11eb-8477-8239d0d0b251.png)

**Comment by proffalken** [comment]
@husseinmarah I've just started using this so I'm not massively familiar with the code yet, however your issues appear to be as follows:

Picture 1:  You're using Python2.7, don't. ;)  This is Python3 code :)

Picture 2: You've not defined your MQTT server correctly or there is a firewall blocking the connection, check those two things and then run it again :)

**Comment by fhemberger** [comment]
Sorry it took so long to get back to you, didn't get any notifications for this repo. 😠 

What Matthew already said, Python 2 has been deprecated since January 2020 and you don't seem to have configured your MQTT server connection correctly. I'm closing this for now, if you still have problems, please feel free to re-open this issue and post your config file as well.

**Comment by husseinmarah** [comment]
Thank you for the "late replay" :)
yes, actually I solve the problem long time ago and I wrote my own exporter, because this seems too complicated ;)
